// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSFawGysL_5xrj-ueewo811-SXSHjS5vk',
    appId: '1:1083109514317:web:a9c3c932667720c0ef1004',
    messagingSenderId: '1083109514317',
    projectId: 'homo-8bd7a',
    authDomain: 'homo-8bd7a.firebaseapp.com',
    storageBucket: 'homo-8bd7a.appspot.com',
    measurementId: 'G-0G0LQQZGZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoSjBUjd0caF7fXG_r3JsF0KzNdxLG7a8',
    appId: '1:1083109514317:android:0007820fbdd981c1ef1004',
    messagingSenderId: '1083109514317',
    projectId: 'homo-8bd7a',
    storageBucket: 'homo-8bd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwavoj7lrrBmG-FcAU8xuE7O4IWhA7Jk',
    appId: '1:1083109514317:ios:4e23541e0114b051ef1004',
    messagingSenderId: '1083109514317',
    projectId: 'homo-8bd7a',
    storageBucket: 'homo-8bd7a.appspot.com',
    iosBundleId: 'com.example.worker',
  );
}
